---
git:
  depth: 1
sudo: false
language: node_js
cache:
  directories:
  - node_modules

node_js:
 - "6"
 - "5"
 - "4"

before_script:
- npm install -g bower
- bower install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
